# Generated by Django 5.1.3 on 2024-12-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelos',
            name='archivo',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='rutas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='velocidad_movimiento',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='volumen',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='modelos',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=50),
        ),
    ]
