# Generated by Django 5.1.3 on 2024-12-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museo', '0002_remove_modelos_archivo_configuracion_rutas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='configuracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='Museo.configuracion'),
        ),
    ]
