# Generated by Django 5.1.3 on 2024-12-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museo', '0003_alter_usuario_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='sensibilidad',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='velocidad_movimiento',
            field=models.SmallIntegerField(default=50),
        ),
    ]
