# Generated by Django 5.1.3 on 2024-12-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Museo', '0004_alter_configuracion_sensibilidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='configuracion',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
        migrations.DeleteModel(
            name='Modelos',
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
