# Generated by Django 5.1.3 on 2024-12-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museo', '0005_delete_articulos_remove_usuario_configuracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('revista', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brillo', models.SmallIntegerField(default=50)),
                ('volumen', models.SmallIntegerField(default=50)),
                ('velocidad_movimiento', models.SmallIntegerField(default=50)),
                ('sensibilidad', models.SmallIntegerField(default=50)),
                ('rutas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(default='Sin dirección', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='configuracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='Museo.configuracion'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='Museo.usuario')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_favoritos', to='Museo.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Museo.usuario')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Museo.modelos')),
            ],
        ),
    ]
